//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Vehicle Owners Database.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VEHICLEOWNERSDATABASE_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_ADDNEWVEHICLE_DIALOG 129
#define IDD_ADDNEWVEHICLE_DIALOG        129
#define IDD_SEARCHOWNER_DIALOG          130
#define IDD_SEARCHREMOVEVEHICLE_DIALOG  131
#define IDD_MAINHELP_DIALOG             132
#define IDD_OWNEDVEHICLES_DIALOG        133
#define IDD_OWNERSEARCHHELP_DIALOG      134
#define IDD_REMOVEVEHICLEHELP_DIALOG    135
#define IDC_STATIC_MAINMENU             1000
#define IDC_BUTTON_ADDANEWVEHICLE       1001
#define IDC_BUTTON_SEARCHOWNERSLIST     1002
#define IDC_BUTTON_ViewOwnersList       1003
#define IDC_BUTTON_RemoveVehicle        1004
#define IDC_BUTTON_SearchVehicleList    1005
#define IDC_BUTTON_SEARCHREMOVEVEHICLE  1005
#define IDABOUT                         1006
#define ID_ABOUT                        1006
#define IDEXIT                          1007
#define IDC_STATIC_OWNERINFORMATION     1008
#define IDC_STATIC_VEHICLEINFORMATION   1009
#define IDC_EDIT_OI_FIRSTNAME           1010
#define IDC_EDIT_OI_LASTNAME            1011
#define IDC_STATIC_OI_FIRSTNAME         1012
#define IDC_STATIC_OI_LASTNAME          1013
#define IDC_STATIC_OI_SIN               1014
#define IDC_EDIT_OI_SIN                 1015
#define IDC_EDIT_OI_TELEPHONENO         1016
#define IDC_STATIC_OI_TELEPHONENO       1017
#define IDC_STATIC_OI_PERMANENTADDRESS  1018
#define IDC_EDIT_OI_PERMANENTADDRESS    1019
#define IDC_EDIT_VI_VEHICLEMAKE         1020
#define IDC_STATIC_VI_VEHICLEMAKE       1021
#define IDC_STATIC_VI_REGISTRATIONNO    1022
#define IDC_STATIC_VI_ENGINESIZE        1023
#define IDC_STATIC_VI_VIN               1024
#define IDC_EDIT_VI_ENGINESIZE          1025
#define IDC_STATIC_Disclaimer           1025
#define IDC_EDIT_VI_REGISTRATIONNO      1026
#define IDC_EDIT_VI_VIN                 1027
#define IDC_STATIC_DisclaimerGroup      1027
#define IDC_BUTTON1                     1028
#define IDC_BUTTON_ADD                  1028
#define IDC_BUTTON_OS_HELP1             1028
#define IDC_BUTTON_PREVIOUS             1028
#define IDC_BUTTON2                     1029
#define IDC_BUTTON_MAINMENU             1029
#define IDC_BUTTON_FIND                 1029
#define IDC_BUTTON_NEXT                 1029
#define IDC_STATIC_SEARCHSPECIFIC       1030
#define IDPREVIOUS                      1031
#define IDC_STATIC_REMOVEPECIFIC        1031
#define IDC_STATIC_Copyrights           1031
#define IDNEXT                          1032
#define IDC_BUTTON_DELETEVEHICLE        1032
#define IDC_STATIC_Warning              1032
#define IDC_EDIT1                       1033
#define IDC_EDIT_SEARCHBYSIN            1033
#define IDC_EDIT_OV_TOTALVEHOCLESOWNED  1033
#define IDC_STATIC_MANUALSEARCHBYTRAVERSING 1034
#define IDC_BUTTON_OI_MAINMENU          1035
#define IDC_BUTTON_OS_HELP              1036
#define IDC_BUTTON_OS_OWNEDVEHICLES     1036
#define IDC_EDIT_SEARCHBYVIN            1038
#define IDC_EDIT_REMOVEVEHICLEBYVIN     1039
#define IDMAINMENU                      1040
#define IDC_EDIT_SRV_VEHICLEMAKE        1041
#define IDC_EDIT_SRV_ENGINESIZE         1042
#define IDC_EDIT_SRV_REGISTRATIONNO     1043
#define IDC_EDIT_SRV_VIN                1045
#define IDC_STATIC_SRV_VEHICLEMAKE      1046
#define IDC_STATIC_SRV_ENGINESIZE       1047
#define IDC_STATIC_SRV_REGISTRATIONNO   1048
#define IDC_STATIC_SRV_VIN              1049
#define IDC_STATIC_ABOUT                1050
#define IDC_STATIC_VERSION              1051
#define IDC_STATIC_AUTHOR               1052
#define IDC_STATIC_ROLLNO               1053
#define IDC_STATIC_DESCRIPTION          1054
#define IDC_STATIC_ADDVEHICLEOWNER      1055
#define IDC_STATIC_ADDVEHICLEOWNERSTRING 1056
#define IDC_STATIC_OV_VEHICLEINFORMATION 1057
#define IDC_STATIC_OV_VEHICLEMAKE       1058
#define IDC_STATIC_SEARCHVIEWOWNER      1059
#define IDC_STATIC_OV_ENGINESIZE        1059
#define IDC_STATIC_SEARCHPRINTOWNERSTRING 1060
#define IDC_STATIC_OV_REGISTRATIONNO    1060
#define IDC_STATIC_SEARCHREMOVEVEHICLE  1061
#define IDC_STATIC_OV_VIN               1061
#define IDC_STATIC_SEARCHREMOVEVEHICLESTRING 1062
#define IDC_EDIT_OV_VEHICLEMAKE         1062
#define IDC_EDIT_OV_ENGINESIZE          1063
#define IDC_EDIT_OV_REGISTRATIONNO      1064
#define IDC_EDIT_OV_VIN                 1065
#define IDC_STATIC_OV_TOTALVEHICLES     1066
#define IDC_HOTKEY1                     1067
#define IDC_STATIC_OWNERSEARCH          1068
#define IDC_STATIC_SEARCHINGOWNERSTRING 1069
#define IDC_STATIC_VIEWINGOWNERLIST     1070
#define IDC_STATIC_VIEWINGOWNEDVEHICLESSTRING 1071
#define IDC_STATIC_REMOVEVEHICLEHELP    1072
#define IDC_STATIC_VIEWREMOVEHELPSTRING 1073

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
